# Generated by Django 4.1.5 on 2023-01-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Category')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL of the category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name of the character')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL of the character')),
                ('anime', models.CharField(blank=True, max_length=255, verbose_name='Name of Anime')),
                ('content', models.TextField(verbose_name='content')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_upload', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='is published?')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Anime Character',
                'verbose_name_plural': 'Anime Characters',
                'ordering': ['time_create', 'name'],
            },
        ),
    ]
